-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 23:43:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema financiera-patito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema financiera-patito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `financiera-patito` DEFAULT CHARACTER SET utf8mb4 ;
USE `financiera-patito` ;

-- -----------------------------------------------------
-- Table `financiera-patito`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financiera-patito`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financiera-patito`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financiera-patito`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `financiera-patito`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financiera-patito`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financiera-patito`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financiera-patito`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financiera-patito`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financiera-patito`.`clientes` (
  `idcliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `apellido_paterno` VARCHAR(60) NULL,
  `apellido_materno` VARCHAR(60) NULL,
  `numero_telefono` VARCHAR(10) NULL,
  `direccion` VARCHAR(60) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financiera-patito`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financiera-patito`.`prestamos` (
  `idprestamos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idcliente` INT(10) UNSIGNED NOT NULL,
  `cantidad` DECIMAL(8,2) NULL,
  `numero_de_pagos` INT(15) NULL,
  `cuota` DECIMAL(8,2) NULL,
  `fecha_de_ministerio` DATE NULL,
  `fecha_de_vencimiento` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idprestamos`),
  INDEX `fk_prestamos_clientes1_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_prestamos_clientes1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `financiera-patito`.`clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financiera-patito`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financiera-patito`.`pagos` (
  `idpagos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idcliente` INT(20) UNSIGNED NOT NULL,
  `idprestamos` INT(20) UNSIGNED NOT NULL,
  `numero` INT(20) NULL,
  `cantidad` DECIMAL(8,2) NULL,
  `fecha_de_pago` DATE NULL,
  `cantidad_recibida` DECIMAL(8,2) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `total` DECIMAL(10) NULL,
  PRIMARY KEY (`idpagos`),
  INDEX `fk_pagos_clientes_idx` (`idcliente` ASC) VISIBLE,
  INDEX `fk_pagos_prestamos1_idx` (`idprestamos` ASC) VISIBLE,
  CONSTRAINT `fk_pagos_clientes`
    FOREIGN KEY (`idcliente`)
    REFERENCES `financiera-patito`.`clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_prestamos1`
    FOREIGN KEY (`idprestamos`)
    REFERENCES `financiera-patito`.`prestamos` (`idprestamos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
